apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: devops-lab
data:
  init.sql: |
    CREATE TABLE tasks (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL
    );

    INSERT INTO tasks (title) VALUES ('Primera tarea');
